name: Build + publish draft release

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      ref:
        description: "ref"
        required: true
        default: "master"

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: kltdwrds/jackjam
          ref: ${{ github.event.inputs.ref }}
      - name: Use Node.js v12.10.0
        uses: actions/setup-node@v1
        with:
          node-version: v12.10.0
      - name: Install jackjam deps
        run: |
          npm install
      - name: Import codesign certs
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.APPLE_DEV_P12 }}
          p12-password: ${{ secrets.APPLE_DEV_P12_PASSWORD }}
          keychain: temp_keychain
      - name: Build jackjam
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.APPLE_DEV_P12 }}
          CSC_KEY_PASSWORD: ${{ secrets.APPLE_DEV_P12_PASSWORD }}
          CSC_KEYCHAIN: temp_keychain
          AC_USERNAME: edwards.ky1@gmail.com
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        run: |
          npm run dist
